version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps):"